// <auto-generated />
using System;
using BidParser.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BidParser.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260523045730_AddParseMetricsLedger")]
    partial class AddParseMetricsLedger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("BidParser.Infrastructure.Entities.ParseJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<decimal>("ComputedTotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("computed_total");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<decimal>("FxRate")
                        .HasPrecision(12, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("fx_rate");

                    b.Property<decimal>("Margin")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("margin");

                    b.Property<string>("OutputPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("output_path");

                    b.Property<string>("ParserSlug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("parser_slug");

                    b.Property<decimal?>("QuotedTotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("quoted_total");

                    b.Property<string>("SourceFilename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT COLLATE NOCASE")
                        .HasColumnName("source_filename");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_path");

                    b.Property<bool>("TotalsMatch")
                        .HasColumnType("INTEGER")
                        .HasColumnName("totals_match");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("vendor");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_parse_jobs_user_id");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_parse_jobs_user_id_created_at");

                    b.ToTable("parse_jobs", (string)null);
                });

            modelBuilder.Entity("BidParser.Infrastructure.Entities.ParseMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<decimal>("ComputedTotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("computed_total");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("currency");

                    b.Property<decimal>("FxRate")
                        .HasPrecision(12, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("fx_rate");

                    b.Property<decimal>("Margin")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("margin");

                    b.Property<int?>("ParseJobId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parse_job_id");

                    b.Property<string>("ParserSlug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("parser_slug");

                    b.Property<decimal?>("QuotedTotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("quoted_total");

                    b.Property<string>("SourceFilename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT COLLATE NOCASE")
                        .HasColumnName("source_filename");

                    b.Property<bool>("TotalsMatch")
                        .HasColumnType("INTEGER")
                        .HasColumnName("totals_match");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.Property<string>("UserUsername")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_username");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("vendor");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_parse_metrics_created_at");

                    b.HasIndex("ParseJobId");

                    b.HasIndex("ParserSlug", "CreatedAt")
                        .HasDatabaseName("ix_parse_metrics_parser_slug_created_at");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_parse_metrics_user_id_created_at");

                    b.HasIndex("Vendor", "CreatedAt")
                        .HasDatabaseName("ix_parse_metrics_vendor_created_at");

                    b.ToTable("parse_metrics", (string)null);
                });

            modelBuilder.Entity("BidParser.Infrastructure.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultVendor")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("default_vendor");

                    b.Property<decimal?>("FxRate")
                        .HasPrecision(12, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("fx_rate");

                    b.Property<decimal?>("Margin")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("margin");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER")
                        .HasColumnName("must_change_password");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT COLLATE NOCASE")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BidParser.Infrastructure.Entities.ParseJob", b =>
                {
                    b.HasOne("BidParser.Infrastructure.Entities.User", "User")
                        .WithMany("ParseJobs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BidParser.Infrastructure.Entities.ParseMetric", b =>
                {
                    b.HasOne("BidParser.Infrastructure.Entities.ParseJob", "ParseJob")
                        .WithMany()
                        .HasForeignKey("ParseJobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BidParser.Infrastructure.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParseJob");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BidParser.Infrastructure.Entities.User", b =>
                {
                    b.Navigation("ParseJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
