// <auto-generated />
using System;
using BidParser.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BidParser.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260529094937_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BidParser.Infrastructure.Entities.FailedParseJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("category");

                    b.Property<decimal?>("ComputedTotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("computed_total");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorDetail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_detail");

                    b.Property<decimal>("FxRate")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("fx_rate");

                    b.Property<string>("Hint")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("hint");

                    b.Property<decimal>("Margin")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("margin");

                    b.Property<string>("Message")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("message");

                    b.Property<string>("ParserSlug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("parser_slug");

                    b.Property<decimal?>("QuotedTotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("quoted_total");

                    b.Property<string>("SourceFilename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("source_filename")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("source_path");

                    b.Property<string>("Stage")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("stage");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("user_name");

                    b.Property<string>("UserUsername")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("user_username");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("vendor");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_failed_parse_jobs_created_at");

                    b.HasIndex("Category", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_failed_parse_jobs_category_created_at");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_failed_parse_jobs_user_id_created_at");

                    b.ToTable("failed_parse_jobs", (string)null);
                });

            modelBuilder.Entity("BidParser.Infrastructure.Entities.ParseJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ComputedTotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("computed_total");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CrmTemplate")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("crm_template");

                    b.Property<decimal>("FxRate")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("fx_rate");

                    b.Property<decimal>("Margin")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("margin");

                    b.Property<string>("OutputPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("output_path");

                    b.Property<string>("ParserSlug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("parser_slug");

                    b.Property<decimal?>("QuotedTotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("quoted_total");

                    b.Property<string>("SourceFilename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("source_filename")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("source_path");

                    b.Property<bool>("TotalsMatch")
                        .HasColumnType("bit")
                        .HasColumnName("totals_match");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("vendor");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_parse_jobs_user_id");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_parse_jobs_user_id_created_at");

                    b.ToTable("parse_jobs", (string)null);
                });

            modelBuilder.Entity("BidParser.Infrastructure.Entities.ParseMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ComputedTotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("computed_total");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency");

                    b.Property<decimal>("FxRate")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("fx_rate");

                    b.Property<decimal>("Margin")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("margin");

                    b.Property<int?>("ParseJobId")
                        .HasColumnType("int")
                        .HasColumnName("parse_job_id");

                    b.Property<string>("ParserSlug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("parser_slug");

                    b.Property<decimal?>("QuotedTotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("quoted_total");

                    b.Property<string>("SourceFilename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("source_filename")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<bool>("TotalsMatch")
                        .HasColumnType("bit")
                        .HasColumnName("totals_match");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("user_name");

                    b.Property<string>("UserUsername")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("user_username");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("vendor");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_parse_metrics_created_at");

                    b.HasIndex("ParseJobId");

                    b.HasIndex("ParserSlug", "CreatedAt")
                        .HasDatabaseName("ix_parse_metrics_parser_slug_created_at");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_parse_metrics_user_id_created_at");

                    b.HasIndex("Vendor", "CreatedAt")
                        .HasDatabaseName("ix_parse_metrics_vendor_created_at");

                    b.ToTable("parse_metrics", (string)null);
                });

            modelBuilder.Entity("BidParser.Infrastructure.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultVendor")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("default_vendor");

                    b.Property<decimal?>("FxRate")
                        .HasPrecision(12, 4)
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("fx_rate");

                    b.Property<decimal?>("ImPercent")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("im");

                    b.Property<decimal?>("Margin")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("margin");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit")
                        .HasColumnName("must_change_password");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("username")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BidParser.Infrastructure.Entities.FailedParseJob", b =>
                {
                    b.HasOne("BidParser.Infrastructure.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("BidParser.Infrastructure.Entities.ParseJob", b =>
                {
                    b.HasOne("BidParser.Infrastructure.Entities.User", "User")
                        .WithMany("ParseJobs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BidParser.Infrastructure.Entities.ParseMetric", b =>
                {
                    b.HasOne("BidParser.Infrastructure.Entities.ParseJob", "ParseJob")
                        .WithMany()
                        .HasForeignKey("ParseJobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BidParser.Infrastructure.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParseJob");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BidParser.Infrastructure.Entities.User", b =>
                {
                    b.Navigation("ParseJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
